### PR TITLE
zookeeper 3.8.0 Deprecate log4j, parameter of ZOO_LOG_LEVEL is inoperative

### PR DESCRIPTION
**Pull request by wangguoyan**
…ative

**Description of the change**
libzookeeper.sh

**Benefits**

zookeeper 3.8.0 use logback and deprecate log4j, the parameter of ZOO_LOG_LEVEL is inoperative in log4j.properties, it should  be applied to logback.xml
**Possible drawbacks**

**Applicable issues**

**Additional information**

### CODE REVIEW

**Comment by alemorcuq** [comment]
Thanks for the PR, @wangguoyan. Do you mind sharing some documentation from Zookeeper on this change?

**Comment by wangguoyan** [comment]
> Thanks for the PR, @wangguoyan. Do you mind sharing some documentation from Zookeeper on this change?
@alemorcuq 
the documentation of this change https://zookeeper.apache.org/releases.html#releasenotes
image

**Comment by alemorcuq** [comment]
Thanks, @wangguoyan. I'm going to create an internal task to manage this PR since we need to add some code internally to support this.

**Comment by wangguoyan** [comment]
> Thanks, @wangguoyan. I'm going to create an internal task to manage this PR since we need to add some code internally to support this.

what  can I do next？

**Comment by carrodher** [comment]
In order to unify the approaches followed for Bitnami containers and Bitnami Helm charts, we are moving the different `bitnami/bitnami-docker-<container>` repositories to a single repository: `bitnami/containers`.

Please could you create this PR in the [`bitnami/containers` monorepository](https://github.com/bitnami/containers)? Thank

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

**Pull request closed without merging**
