### PR TITLE
Add preAllocSize and snapCount configuration options

### PR DESCRIPTION
**Pull request by francescsanjuanmrf**
**Description of the change**

Add support to modify preAllocSize and snapCount configuration parameters.

**Benefits**

Allow parameter modification.

**Possible drawbacks**

I can't see any drawback. The default values in Docker image are the zookeeper default values.

**Applicable issues**

No applicable issues

### CODE REVIEW

**Comment by francescsanjuanmrf** [comment]
Sorry, still not well tested.

**Review by miguelaeh — COMMENTED** [review]
Hi @francescsanjuanmrf ,
Sorry for the late response, we missed this card.
Could you explain why are you using those default values? Are they the default values if you don't set those variables?

**Comment by francescsanjuanmrf** [comment]
Hi @miguelaeh ,

Sorry, I've forgotten about this. From the documentation, the default values for snapcount and preAllocSize. if they are not set, are the same that in this PR:

snapcount: 100000
preAllocSize: 64MB (65536 KB)

https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html

**Review by miguelaeh — APPROVED** [review]
LGTM!

**Pull request merged**
